import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import Videos from '../components/Videos'
import { useAuth } from '../context/AuthContext'

export default function Home() {
  const { currentUser } = useAuth()

  return (
    < >
      <Head>
        <title>Video List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <Videos/>}
    </>
  )
}
